In [48]:
import pandas as pd
import numpy as np

In [12]:
df = pd.read_csv('flipkart_mobile.csv')
df.head(10)

,Unnamed: 0,brand name,rating & review,star rating,discount,other info
0,0,"REDMI 11 Prime 5G (Meadow Green, 64 GB)","4,687 Ratings & 262 Reviews",4.2,NaN,4 GB RAM | 64 GB ROM\r\n16.71 cm (6.58 inch) D...
1,1,"realme GT 8 Pro (Diary White, 512 GB)",99 Ratings & 19 Reviews,4.5,9% off,16 GB RAM | 512 GB ROM\r\n17.25 cm (6.79 inch)...
2,2,"OnePlus 11 5G (Eternal Green, 256 GB)","1,900 Ratings & 165 Reviews",4.5,NaN,16 GB RAM | 256 GB ROM\r\n17.02 cm (6.7 inch) ...
3,3,"IQOO Z11 Lite 5G (Solar Flame, 256 GB)",NaN,NaN,22% off,6 GB RAM | 256 GB ROM\r\n17.12 cm (6.74 inch) ...
4,4,"realme P4R 5G (Silver Glare, 128 GB)","3,219 Ratings & 259 Reviews",4.4,45% off,6 GB RAM | 128 GB ROM\r\n17.27 cm (6.8 inch) H...
5,5,"realme P4 Lite 5G (Mosaic Blue, 64 GB)","11,802 Ratings & 755 Reviews",4.2,43% off,4 GB RAM | 64 GB ROM\r\n17.27 cm (6.8 inches) ...
6,6,"vivo V70 (Passion Red 2026, 256 GB)","1,589 Ratings & 192 Reviews",4.6,9% off,8 GB RAM | 256 GB ROM\r\n16.74 cm (6.59 inches...
7,7,"vivo V70 (Lemon Yellow 2026, 256 GB)","1,589 Ratings & 192 Reviews",4.6,9% off,8 GB RAM | 256 GB ROM\r\n16.74 cm (6.59 inches...
8,8,"vivo X200T (Seaside Lilac, 256 GB)","7,826 Ratings & 1,562 Reviews",4.6,25% off,12 GB RAM | 256 GB ROM\r\n16.94 cm (6.67 inch)...
9,9,"realme P4 Power 5G (TransSilver, 128 GB)","7,149 Ratings & 749 Reviews",4.4,9% off,8 GB RAM | 128 GB ROM\r\n17.27 cm (6.8 inch) F...

In [13]:
df = df.drop(columns=['Unnamed: 0'])

In [14]:
df.insert(0, 'model name' ,df['brand name'].str.split('(').str[0])

In [15]:
df

,model name,brand name,rating & review,star rating,discount,other info
0,REDMI 11 Prime 5G,"REDMI 11 Prime 5G (Meadow Green, 64 GB)","4,687 Ratings & 262 Reviews",4.2,NaN,4 GB RAM | 64 GB ROM\r\n16.71 cm (6.58 inch) D...
1,realme GT 8 Pro,"realme GT 8 Pro (Diary White, 512 GB)",99 Ratings & 19 Reviews,4.5,9% off,16 GB RAM | 512 GB ROM\r\n17.25 cm (6.79 inch)...
2,OnePlus 11 5G,"OnePlus 11 5G (Eternal Green, 256 GB)","1,900 Ratings & 165 Reviews",4.5,NaN,16 GB RAM | 256 GB ROM\r\n17.02 cm (6.7 inch) ...
3,IQOO Z11 Lite 5G,"IQOO Z11 Lite 5G (Solar Flame, 256 GB)",NaN,NaN,22% off,6 GB RAM | 256 GB ROM\r\n17.12 cm (6.74 inch) ...
4,realme P4R 5G,"realme P4R 5G (Silver Glare, 128 GB)","3,219 Ratings & 259 Reviews",4.4,45% off,6 GB RAM | 128 GB ROM\r\n17.27 cm (6.8 inch) H...
...,...,...,...,...,...,...
91,realme 16 Pro+ 5G,"realme 16 Pro+ 5G (Master Grey, 256 GB)",855 Ratings & 123 Reviews,4.6,5% off,12 GB RAM | 256 GB ROM\r\n17.27 cm (6.8 inch) ...
92,IQOO 15R 5G,"IQOO 15R 5G (Dark Knight, 256 GB)",330 Ratings & 42 Reviews,4.7,3% off,8 GB RAM | 256 GB ROM\r\n16.74 cm (6.59 inch) ...
93,Samsung Galaxy S24 5G Snapdragon,"Samsung Galaxy S24 5G Snapdragon (Onyx Black, ...","57,433 Ratings & 4,568 Reviews",4.6,33% off,8 GB RAM | 128 GB ROM\r\n15.75 cm (6.2 inch) F...
94,OPPO Reno16 5G,"OPPO Reno16 5G (Starry White, 256 GB)",37 Ratings & 9 Reviews,4.4,32% off,12 GB RAM | 256 GB ROM\r\n16.05 cm (6.32 inch)...
95,Ai+ Nova 2 Neo 5G,"Ai+ Nova 2 Neo 5G (Red, 64 GB)",987 Ratings & 109 Reviews,4.4,22% off,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB\r\...

In [26]:
temp = df['brand name'].str.split('(').str[1]
color = temp.str.split(',').str[0]


temp = temp.str.split(',').str[1]
storage = temp.str.replace(')', '')


df.insert(1, 'model color', color)
df.insert(2, 'storage', storage)

In [28]:
df = df.drop(columns='brand name')

In [29]:
df

,model name,model color,storage,rating & review,star rating,discount,other info
0,REDMI 11 Prime 5G,Meadow Green,64 GB,"4,687 Ratings & 262 Reviews",4.2,NaN,4 GB RAM | 64 GB ROM\r\n16.71 cm (6.58 inch) D...
1,realme GT 8 Pro,Diary White,512 GB,99 Ratings & 19 Reviews,4.5,9% off,16 GB RAM | 512 GB ROM\r\n17.25 cm (6.79 inch)...
2,OnePlus 11 5G,Eternal Green,256 GB,"1,900 Ratings & 165 Reviews",4.5,NaN,16 GB RAM | 256 GB ROM\r\n17.02 cm (6.7 inch) ...
3,IQOO Z11 Lite 5G,Solar Flame,256 GB,NaN,NaN,22% off,6 GB RAM | 256 GB ROM\r\n17.12 cm (6.74 inch) ...
4,realme P4R 5G,Silver Glare,128 GB,"3,219 Ratings & 259 Reviews",4.4,45% off,6 GB RAM | 128 GB ROM\r\n17.27 cm (6.8 inch) H...
...,...,...,...,...,...,...,...
91,realme 16 Pro+ 5G,Master Grey,256 GB,855 Ratings & 123 Reviews,4.6,5% off,12 GB RAM | 256 GB ROM\r\n17.27 cm (6.8 inch) ...
92,IQOO 15R 5G,Dark Knight,256 GB,330 Ratings & 42 Reviews,4.7,3% off,8 GB RAM | 256 GB ROM\r\n16.74 cm (6.59 inch) ...
93,Samsung Galaxy S24 5G Snapdragon,Onyx Black,128 GB,"57,433 Ratings & 4,568 Reviews",4.6,33% off,8 GB RAM | 128 GB ROM\r\n15.75 cm (6.2 inch) F...
94,OPPO Reno16 5G,Starry White,256 GB,37 Ratings & 9 Reviews,4.4,32% off,12 GB RAM | 256 GB ROM\r\n16.05 cm (6.32 inch)...
95,Ai+ Nova 2 Neo 5G,Red,64 GB,987 Ratings & 109 Reviews,4.4,22% off,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB\r\...

In [46]:
rating = df['rating & review'].str.split('&').str[0]
rating = rating.str.replace('Ratings', '').str.strip()

review = df['rating & review'].str.split('&').str[1]
review = review.str.replace('Reviews', '').str.strip()

df.insert(3, 'review', review)
df.insert(4, 'rating', rating)

In [50]:
df.drop(columns='rating & review', inplace=True)

In [51]:
df.replace('NaN', np.nan, inplace=True)

,model name,model color,storage,review,rating,star rating,discount,other info
0,REDMI 11 Prime 5G,Meadow Green,64 GB,262,"4,687",4.2,NaN,4 GB RAM | 64 GB ROM\r\n16.71 cm (6.58 inch) D...
1,realme GT 8 Pro,Diary White,512 GB,19,99,4.5,9% off,16 GB RAM | 512 GB ROM\r\n17.25 cm (6.79 inch)...
2,OnePlus 11 5G,Eternal Green,256 GB,165,"1,900",4.5,NaN,16 GB RAM | 256 GB ROM\r\n17.02 cm (6.7 inch) ...
3,IQOO Z11 Lite 5G,Solar Flame,256 GB,NaN,NaN,NaN,22% off,6 GB RAM | 256 GB ROM\r\n17.12 cm (6.74 inch) ...
4,realme P4R 5G,Silver Glare,128 GB,259,"3,219",4.4,45% off,6 GB RAM | 128 GB ROM\r\n17.27 cm (6.8 inch) H...
...,...,...,...,...,...,...,...,...
91,realme 16 Pro+ 5G,Master Grey,256 GB,123,855,4.6,5% off,12 GB RAM | 256 GB ROM\r\n17.27 cm (6.8 inch) ...
92,IQOO 15R 5G,Dark Knight,256 GB,42,330,4.7,3% off,8 GB RAM | 256 GB ROM\r\n16.74 cm (6.59 inch) ...
93,Samsung Galaxy S24 5G Snapdragon,Onyx Black,128 GB,"4,568","57,433",4.6,33% off,8 GB RAM | 128 GB ROM\r\n15.75 cm (6.2 inch) F...
94,OPPO Reno16 5G,Starry White,256 GB,9,37,4.4,32% off,12 GB RAM | 256 GB ROM\r\n16.05 cm (6.32 inch)...
95,Ai+ Nova 2 Neo 5G,Red,64 GB,109,987,4.4,22% off,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB\r\...

In [ ]:
# because if no one give review and rating the value will show 0 thats why i removed the null 

df[['review', 'rating']] = df[['review', 'rating']].replace(['NaN', np.nan], '0')

In [56]:
df

,model name,model color,storage,review,rating,star rating,discount,other info
0,REDMI 11 Prime 5G,Meadow Green,64 GB,262,"4,687",4.2,NaN,4 GB RAM | 64 GB ROM\r\n16.71 cm (6.58 inch) D...
1,realme GT 8 Pro,Diary White,512 GB,19,99,4.5,9% off,16 GB RAM | 512 GB ROM\r\n17.25 cm (6.79 inch)...
2,OnePlus 11 5G,Eternal Green,256 GB,165,"1,900",4.5,NaN,16 GB RAM | 256 GB ROM\r\n17.02 cm (6.7 inch) ...
3,IQOO Z11 Lite 5G,Solar Flame,256 GB,0,0,NaN,22% off,6 GB RAM | 256 GB ROM\r\n17.12 cm (6.74 inch) ...
4,realme P4R 5G,Silver Glare,128 GB,259,"3,219",4.4,45% off,6 GB RAM | 128 GB ROM\r\n17.27 cm (6.8 inch) H...
...,...,...,...,...,...,...,...,...
91,realme 16 Pro+ 5G,Master Grey,256 GB,123,855,4.6,5% off,12 GB RAM | 256 GB ROM\r\n17.27 cm (6.8 inch) ...
92,IQOO 15R 5G,Dark Knight,256 GB,42,330,4.7,3% off,8 GB RAM | 256 GB ROM\r\n16.74 cm (6.59 inch) ...
93,Samsung Galaxy S24 5G Snapdragon,Onyx Black,128 GB,"4,568","57,433",4.6,33% off,8 GB RAM | 128 GB ROM\r\n15.75 cm (6.2 inch) F...
94,OPPO Reno16 5G,Starry White,256 GB,9,37,4.4,32% off,12 GB RAM | 256 GB ROM\r\n16.05 cm (6.32 inch)...
95,Ai+ Nova 2 Neo 5G,Red,64 GB,109,987,4.4,22% off,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB\r\...

In [58]:
df['star rating'] = df['star rating'].replace(np.nan, 0.0)

In [59]:
df

,model name,model color,storage,review,rating,star rating,discount,other info
0,REDMI 11 Prime 5G,Meadow Green,64 GB,262,"4,687",4.2,NaN,4 GB RAM | 64 GB ROM\r\n16.71 cm (6.58 inch) D...
1,realme GT 8 Pro,Diary White,512 GB,19,99,4.5,9% off,16 GB RAM | 512 GB ROM\r\n17.25 cm (6.79 inch)...
2,OnePlus 11 5G,Eternal Green,256 GB,165,"1,900",4.5,NaN,16 GB RAM | 256 GB ROM\r\n17.02 cm (6.7 inch) ...
3,IQOO Z11 Lite 5G,Solar Flame,256 GB,0,0,0.0,22% off,6 GB RAM | 256 GB ROM\r\n17.12 cm (6.74 inch) ...
4,realme P4R 5G,Silver Glare,128 GB,259,"3,219",4.4,45% off,6 GB RAM | 128 GB ROM\r\n17.27 cm (6.8 inch) H...
...,...,...,...,...,...,...,...,...
91,realme 16 Pro+ 5G,Master Grey,256 GB,123,855,4.6,5% off,12 GB RAM | 256 GB ROM\r\n17.27 cm (6.8 inch) ...
92,IQOO 15R 5G,Dark Knight,256 GB,42,330,4.7,3% off,8 GB RAM | 256 GB ROM\r\n16.74 cm (6.59 inch) ...
93,Samsung Galaxy S24 5G Snapdragon,Onyx Black,128 GB,"4,568","57,433",4.6,33% off,8 GB RAM | 128 GB ROM\r\n15.75 cm (6.2 inch) F...
94,OPPO Reno16 5G,Starry White,256 GB,9,37,4.4,32% off,12 GB RAM | 256 GB ROM\r\n16.05 cm (6.32 inch)...
95,Ai+ Nova 2 Neo 5G,Red,64 GB,109,987,4.4,22% off,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB\r\...

In [60]:
df['discount']= df['discount'].replace(np.nan, 'No Discount')

In [61]:
df

,model name,model color,storage,review,rating,star rating,discount,other info
0,REDMI 11 Prime 5G,Meadow Green,64 GB,262,"4,687",4.2,No Discount,4 GB RAM | 64 GB ROM\r\n16.71 cm (6.58 inch) D...
1,realme GT 8 Pro,Diary White,512 GB,19,99,4.5,9% off,16 GB RAM | 512 GB ROM\r\n17.25 cm (6.79 inch)...
2,OnePlus 11 5G,Eternal Green,256 GB,165,"1,900",4.5,No Discount,16 GB RAM | 256 GB ROM\r\n17.02 cm (6.7 inch) ...
3,IQOO Z11 Lite 5G,Solar Flame,256 GB,0,0,0.0,22% off,6 GB RAM | 256 GB ROM\r\n17.12 cm (6.74 inch) ...
4,realme P4R 5G,Silver Glare,128 GB,259,"3,219",4.4,45% off,6 GB RAM | 128 GB ROM\r\n17.27 cm (6.8 inch) H...
...,...,...,...,...,...,...,...,...
91,realme 16 Pro+ 5G,Master Grey,256 GB,123,855,4.6,5% off,12 GB RAM | 256 GB ROM\r\n17.27 cm (6.8 inch) ...
92,IQOO 15R 5G,Dark Knight,256 GB,42,330,4.7,3% off,8 GB RAM | 256 GB ROM\r\n16.74 cm (6.59 inch) ...
93,Samsung Galaxy S24 5G Snapdragon,Onyx Black,128 GB,"4,568","57,433",4.6,33% off,8 GB RAM | 128 GB ROM\r\n15.75 cm (6.2 inch) F...
94,OPPO Reno16 5G,Starry White,256 GB,9,37,4.4,32% off,12 GB RAM | 256 GB ROM\r\n16.05 cm (6.32 inch)...
95,Ai+ Nova 2 Neo 5G,Red,64 GB,109,987,4.4,22% off,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB\r\...

In [66]:
pd.set_option('display.max_colwidth', None)
df['other info']

0                                                                                                                                                              4 GB RAM | 64 GB ROM\r\n16.71 cm (6.58 inch) Display\r\n5MP Rear Camera\r\n5000 mAh Battery\r\n1 Year Warranty
1                            16 GB RAM | 512 GB ROM\r\n17.25 cm (6.79 inch) Quad HD+ Display\r\n50MP + 50MP + 200MP | 32MP Front Camera\r\n7000 mAh Battery\r\n8 Elite Gen 5 Processor\r\n1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In-Box Accessories
2                                                                                                          16 GB RAM | 256 GB ROM\r\n17.02 cm (6.7 inch) Display\r\n50MP Rear Camera\r\n5000 mAh Battery\r\ndomestic warranty of 12 months on phone & 6 months on accessories
3                                                                                         6 GB RAM | 256 GB ROM\r\n17.12 cm (6.74 inch) Display\r\n50MP Rear Camera\r\n6500 mAh Battery\r\nMediatek Dimensity 6300 Processor\r\nOne Year of Handset six months of Accessories
4     6 GB RAM | 128 GB ROM\r\n17.27 cm (6.8 inch) HD+ Display\r\n50MP Rear Camera | 8MP Front Camera\r\n8000 mAh Lithium-ion polymer Battery\r\nDimensity 6300 Processor\r\n1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for Inbox Accessories
                                                                                                                                       ...
91                            12 GB RAM | 256 GB ROM\r\n17.27 cm (6.8 inch) Full HD+ AMOLED Display\r\n200MP + 50MP + 8MP | 50MP Front Camera\r\n7000 mAh Battery\r\n7 Gen 4 Processor\r\n1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In-Box Accessories
92                                                                                                                                                  8 GB RAM | 256 GB ROM\r\n16.74 cm (6.59 inch) Display\r\n50MP Rear Camera\r\n7600 mAh Battery\r\n12 Months Brand Warranty
93                                                   8 GB RAM | 128 GB ROM\r\n15.75 cm (6.2 inch) Full HD+ Display\r\n50MP + 12MP | 12MP Front Camera\r\n4000 mAh Battery\r\n8 Gen 3 Processor\r\n1 Year Manufacturer Warranty for Device and 6 Months for In-Box Accessories
94                                  12 GB RAM | 256 GB ROM\r\n16.05 cm (6.32 inch) Full HD+ Display\r\n50MP + 50MP + 50MP | 50MP Front Camera\r\n6700 mAh lithium-ion polymer Battery\r\n7 Gen 4 Processor\r\n1 Year Warranty on Handset and 6 Months Warranty on Accessories
95            4 GB RAM | 64 GB ROM | Expandable Upto 2 TB\r\n17.13 cm (6.745 inch) HD+ Display\r\n48MP Rear Camera | 8MP Front Camera\r\n6000 mAh Li-polymer Battery\r\nDimensity 6300 Processor\r\n1 Year Warranty on Handset and 6 Months Warranty on the Inbox Accessories
Name: other info, Length: 96, dtype: str