In [194]:
import pandas as pd
import numpy as np

In [195]:
df = pd.read_csv('flipkart_mobile.csv')
df.head(10)

,Unnamed: 0,brand name,rating & review,star rating,discount,other info
0,0,"REDMI 11 Prime 5G (Meadow Green, 64 GB)","4,687 Ratings & 262 Reviews",4.2,NaN,4 GB RAM | 64 GB ROM\r\n16.71 cm (6.58 inch) Display\r\n5MP Rear Camera\r\n5000 mAh Battery\r\n1 Year Warranty
1,1,"realme GT 8 Pro (Diary White, 512 GB)",99 Ratings & 19 Reviews,4.5,9% off,16 GB RAM | 512 GB ROM\r\n17.25 cm (6.79 inch) Quad HD+ Display\r\n50MP + 50MP + 200MP | 32MP Front Camera\r\n7000 mAh Battery\r\n8 Elite Gen 5 Processor\r\n1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In-Box Accessories
2,2,"OnePlus 11 5G (Eternal Green, 256 GB)","1,900 Ratings & 165 Reviews",4.5,NaN,16 GB RAM | 256 GB ROM\r\n17.02 cm (6.7 inch) Display\r\n50MP Rear Camera\r\n5000 mAh Battery\r\ndomestic warranty of 12 months on phone & 6 months on accessories
3,3,"IQOO Z11 Lite 5G (Solar Flame, 256 GB)",NaN,NaN,22% off,6 GB RAM | 256 GB ROM\r\n17.12 cm (6.74 inch) Display\r\n50MP Rear Camera\r\n6500 mAh Battery\r\nMediatek Dimensity 6300 Processor\r\nOne Year of Handset six months of Accessories
4,4,"realme P4R 5G (Silver Glare, 128 GB)","3,219 Ratings & 259 Reviews",4.4,45% off,6 GB RAM | 128 GB ROM\r\n17.27 cm (6.8 inch) HD+ Display\r\n50MP Rear Camera | 8MP Front Camera\r\n8000 mAh Lithium-ion polymer Battery\r\nDimensity 6300 Processor\r\n1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for Inbox Accessories
5,5,"realme P4 Lite 5G (Mosaic Blue, 64 GB)","11,802 Ratings & 755 Reviews",4.2,43% off,4 GB RAM | 64 GB ROM\r\n17.27 cm (6.8 inches) HD+ Display\r\n13MP Rear Camera | 5MP Front Camera\r\n7000 mAh lithium-ion polymer Battery\r\nDimensity 6300 Processor\r\n1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for Inbox Accessories
6,6,"vivo V70 (Passion Red 2026, 256 GB)","1,589 Ratings & 192 Reviews",4.6,9% off,8 GB RAM | 256 GB ROM\r\n16.74 cm (6.59 inches) Full HD+ AMOLED Display\r\n50MP + 50MP + 8MP | 50MP Front Camera\r\n6500 mAh Li-ion battery Battery\r\nSnapdragon 7 Gen 4 Processor\r\n1 Year Warranty on Handset and 6 Months Warranty on Accessories
7,7,"vivo V70 (Lemon Yellow 2026, 256 GB)","1,589 Ratings & 192 Reviews",4.6,9% off,8 GB RAM | 256 GB ROM\r\n16.74 cm (6.59 inches) Full HD+ AMOLED Display\r\n50MP + 50MP + 8MP | 50MP Front Camera\r\n6500 mAh Li-ion battery Battery\r\nSnapdragon 7 Gen 4 Processor\r\n1 Year Warranty on Handset and 6 Months Warranty on Accessories
8,8,"vivo X200T (Seaside Lilac, 256 GB)","7,826 Ratings & 1,562 Reviews",4.6,25% off,12 GB RAM | 256 GB ROM\r\n16.94 cm (6.67 inch) Full HD+ AMOLED Display\r\n50MP + 50MP + 50MP | 32MP Front Camera\r\n6200 mAh Battery\r\nDimensity 9400+ Processor\r\n1 Year Warranty on Handset and 6 Months Warranty on Accessories
9,9,"realme P4 Power 5G (TransSilver, 128 GB)","7,149 Ratings & 749 Reviews",4.4,9% off,8 GB RAM | 128 GB ROM\r\n17.27 cm (6.8 inch) Full HD+ AMOLED Display\r\n50MP + 8MP | Yes\r\n10001 mAh Battery\r\nDimensity 7400 Ultra Processor\r\n1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for Inbox Accessories

In [196]:
df = df.drop(columns=['Unnamed: 0'])

In [197]:
df.insert(0, 'model name' ,df['brand name'].str.split('(').str[0])

In [198]:
df.head()

,model name,brand name,rating & review,star rating,discount,other info
0,REDMI 11 Prime 5G,"REDMI 11 Prime 5G (Meadow Green, 64 GB)","4,687 Ratings & 262 Reviews",4.2,NaN,4 GB RAM | 64 GB ROM\r\n16.71 cm (6.58 inch) Display\r\n5MP Rear Camera\r\n5000 mAh Battery\r\n1 Year Warranty
1,realme GT 8 Pro,"realme GT 8 Pro (Diary White, 512 GB)",99 Ratings & 19 Reviews,4.5,9% off,16 GB RAM | 512 GB ROM\r\n17.25 cm (6.79 inch) Quad HD+ Display\r\n50MP + 50MP + 200MP | 32MP Front Camera\r\n7000 mAh Battery\r\n8 Elite Gen 5 Processor\r\n1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In-Box Accessories
2,OnePlus 11 5G,"OnePlus 11 5G (Eternal Green, 256 GB)","1,900 Ratings & 165 Reviews",4.5,NaN,16 GB RAM | 256 GB ROM\r\n17.02 cm (6.7 inch) Display\r\n50MP Rear Camera\r\n5000 mAh Battery\r\ndomestic warranty of 12 months on phone & 6 months on accessories
3,IQOO Z11 Lite 5G,"IQOO Z11 Lite 5G (Solar Flame, 256 GB)",NaN,NaN,22% off,6 GB RAM | 256 GB ROM\r\n17.12 cm (6.74 inch) Display\r\n50MP Rear Camera\r\n6500 mAh Battery\r\nMediatek Dimensity 6300 Processor\r\nOne Year of Handset six months of Accessories
4,realme P4R 5G,"realme P4R 5G (Silver Glare, 128 GB)","3,219 Ratings & 259 Reviews",4.4,45% off,6 GB RAM | 128 GB ROM\r\n17.27 cm (6.8 inch) HD+ Display\r\n50MP Rear Camera | 8MP Front Camera\r\n8000 mAh Lithium-ion polymer Battery\r\nDimensity 6300 Processor\r\n1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for Inbox Accessories

In [199]:
temp = df['brand name'].str.split('(').str[1]
color = temp.str.split(',').str[0]


temp = temp.str.split(',').str[1]
storage = temp.str.replace(')', '')


df.insert(1, 'model color', color)
df.insert(2, 'storage', storage)

In [200]:
df = df.drop(columns='brand name')

In [201]:
rating = df['rating & review'].str.split('&').str[0]
rating = rating.str.replace('Ratings', '').str.strip()

review = df['rating & review'].str.split('&').str[1]
review = review.str.replace('Reviews', '').str.strip()

df.insert(3, 'review', review)
df.insert(4, 'rating', rating)

In [202]:
df.drop(columns='rating & review', inplace=True)

In [203]:
df.replace('NaN', np.nan, inplace=True).head()

,model name,model color,storage,review,rating,star rating,discount,other info
0,REDMI 11 Prime 5G,Meadow Green,64 GB,262,"4,687",4.2,NaN,4 GB RAM | 64 GB ROM\r\n16.71 cm (6.58 inch) Display\r\n5MP Rear Camera\r\n5000 mAh Battery\r\n1 Year Warranty
1,realme GT 8 Pro,Diary White,512 GB,19,99,4.5,9% off,16 GB RAM | 512 GB ROM\r\n17.25 cm (6.79 inch) Quad HD+ Display\r\n50MP + 50MP + 200MP | 32MP Front Camera\r\n7000 mAh Battery\r\n8 Elite Gen 5 Processor\r\n1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In-Box Accessories
2,OnePlus 11 5G,Eternal Green,256 GB,165,"1,900",4.5,NaN,16 GB RAM | 256 GB ROM\r\n17.02 cm (6.7 inch) Display\r\n50MP Rear Camera\r\n5000 mAh Battery\r\ndomestic warranty of 12 months on phone & 6 months on accessories
3,IQOO Z11 Lite 5G,Solar Flame,256 GB,NaN,NaN,NaN,22% off,6 GB RAM | 256 GB ROM\r\n17.12 cm (6.74 inch) Display\r\n50MP Rear Camera\r\n6500 mAh Battery\r\nMediatek Dimensity 6300 Processor\r\nOne Year of Handset six months of Accessories
4,realme P4R 5G,Silver Glare,128 GB,259,"3,219",4.4,45% off,6 GB RAM | 128 GB ROM\r\n17.27 cm (6.8 inch) HD+ Display\r\n50MP Rear Camera | 8MP Front Camera\r\n8000 mAh Lithium-ion polymer Battery\r\nDimensity 6300 Processor\r\n1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for Inbox Accessories

In [204]:
# because if no one give review and rating the value will show 0 thats why i removed the null 

df[['review', 'rating']] = df[['review', 'rating']].replace(['NaN', np.nan], '0')

In [205]:
df.head(5)

,model name,model color,storage,review,rating,star rating,discount,other info
0,REDMI 11 Prime 5G,Meadow Green,64 GB,262,"4,687",4.2,NaN,4 GB RAM | 64 GB ROM\r\n16.71 cm (6.58 inch) Display\r\n5MP Rear Camera\r\n5000 mAh Battery\r\n1 Year Warranty
1,realme GT 8 Pro,Diary White,512 GB,19,99,4.5,9% off,16 GB RAM | 512 GB ROM\r\n17.25 cm (6.79 inch) Quad HD+ Display\r\n50MP + 50MP + 200MP | 32MP Front Camera\r\n7000 mAh Battery\r\n8 Elite Gen 5 Processor\r\n1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In-Box Accessories
2,OnePlus 11 5G,Eternal Green,256 GB,165,"1,900",4.5,NaN,16 GB RAM | 256 GB ROM\r\n17.02 cm (6.7 inch) Display\r\n50MP Rear Camera\r\n5000 mAh Battery\r\ndomestic warranty of 12 months on phone & 6 months on accessories
3,IQOO Z11 Lite 5G,Solar Flame,256 GB,0,0,NaN,22% off,6 GB RAM | 256 GB ROM\r\n17.12 cm (6.74 inch) Display\r\n50MP Rear Camera\r\n6500 mAh Battery\r\nMediatek Dimensity 6300 Processor\r\nOne Year of Handset six months of Accessories
4,realme P4R 5G,Silver Glare,128 GB,259,"3,219",4.4,45% off,6 GB RAM | 128 GB ROM\r\n17.27 cm (6.8 inch) HD+ Display\r\n50MP Rear Camera | 8MP Front Camera\r\n8000 mAh Lithium-ion polymer Battery\r\nDimensity 6300 Processor\r\n1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for Inbox Accessories

In [206]:
df['star rating'] = df['star rating'].replace(np.nan, 0.0)

In [207]:
df.head(5)

,model name,model color,storage,review,rating,star rating,discount,other info
0,REDMI 11 Prime 5G,Meadow Green,64 GB,262,"4,687",4.2,NaN,4 GB RAM | 64 GB ROM\r\n16.71 cm (6.58 inch) Display\r\n5MP Rear Camera\r\n5000 mAh Battery\r\n1 Year Warranty
1,realme GT 8 Pro,Diary White,512 GB,19,99,4.5,9% off,16 GB RAM | 512 GB ROM\r\n17.25 cm (6.79 inch) Quad HD+ Display\r\n50MP + 50MP + 200MP | 32MP Front Camera\r\n7000 mAh Battery\r\n8 Elite Gen 5 Processor\r\n1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In-Box Accessories
2,OnePlus 11 5G,Eternal Green,256 GB,165,"1,900",4.5,NaN,16 GB RAM | 256 GB ROM\r\n17.02 cm (6.7 inch) Display\r\n50MP Rear Camera\r\n5000 mAh Battery\r\ndomestic warranty of 12 months on phone & 6 months on accessories
3,IQOO Z11 Lite 5G,Solar Flame,256 GB,0,0,0.0,22% off,6 GB RAM | 256 GB ROM\r\n17.12 cm (6.74 inch) Display\r\n50MP Rear Camera\r\n6500 mAh Battery\r\nMediatek Dimensity 6300 Processor\r\nOne Year of Handset six months of Accessories
4,realme P4R 5G,Silver Glare,128 GB,259,"3,219",4.4,45% off,6 GB RAM | 128 GB ROM\r\n17.27 cm (6.8 inch) HD+ Display\r\n50MP Rear Camera | 8MP Front Camera\r\n8000 mAh Lithium-ion polymer Battery\r\nDimensity 6300 Processor\r\n1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for Inbox Accessories

In [208]:
df['discount']= df['discount'].replace(np.nan, 'No Discount')

In [209]:
df.head(3)

,model name,model color,storage,review,rating,star rating,discount,other info
0,REDMI 11 Prime 5G,Meadow Green,64 GB,262,"4,687",4.2,No Discount,4 GB RAM | 64 GB ROM\r\n16.71 cm (6.58 inch) Display\r\n5MP Rear Camera\r\n5000 mAh Battery\r\n1 Year Warranty
1,realme GT 8 Pro,Diary White,512 GB,19,99,4.5,9% off,16 GB RAM | 512 GB ROM\r\n17.25 cm (6.79 inch) Quad HD+ Display\r\n50MP + 50MP + 200MP | 32MP Front Camera\r\n7000 mAh Battery\r\n8 Elite Gen 5 Processor\r\n1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In-Box Accessories
2,OnePlus 11 5G,Eternal Green,256 GB,165,"1,900",4.5,No Discount,16 GB RAM | 256 GB ROM\r\n17.02 cm (6.7 inch) Display\r\n50MP Rear Camera\r\n5000 mAh Battery\r\ndomestic warranty of 12 months on phone & 6 months on accessories

In [210]:
pd.set_option('display.max_colwidth', None)
df['other info'].head(20)

0                                                                                                                                                               4 GB RAM | 64 GB ROM\r\n16.71 cm (6.58 inch) Display\r\n5MP Rear Camera\r\n5000 mAh Battery\r\n1 Year Warranty
1                             16 GB RAM | 512 GB ROM\r\n17.25 cm (6.79 inch) Quad HD+ Display\r\n50MP + 50MP + 200MP | 32MP Front Camera\r\n7000 mAh Battery\r\n8 Elite Gen 5 Processor\r\n1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In-Box Accessories
2                                                                                                           16 GB RAM | 256 GB ROM\r\n17.02 cm (6.7 inch) Display\r\n50MP Rear Camera\r\n5000 mAh Battery\r\ndomestic warranty of 12 months on phone & 6 months on accessories
3                                                                                          6 GB RAM | 256 GB ROM\r\n17.12 cm (6.74 inch) Display\r\n50MP Rear Camera\r\n6500 mAh Battery\r\nMediatek Dimensity 6300 Processor\r\nOne Year of Handset six months of Accessories
4      6 GB RAM | 128 GB ROM\r\n17.27 cm (6.8 inch) HD+ Display\r\n50MP Rear Camera | 8MP Front Camera\r\n8000 mAh Lithium-ion polymer Battery\r\nDimensity 6300 Processor\r\n1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for Inbox Accessories
5     4 GB RAM | 64 GB ROM\r\n17.27 cm (6.8 inches) HD+ Display\r\n13MP Rear Camera | 5MP Front Camera\r\n7000 mAh lithium-ion polymer Battery\r\nDimensity 6300 Processor\r\n1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for Inbox Accessories
6                       8 GB RAM | 256 GB ROM\r\n16.74 cm (6.59 inches) Full HD+ AMOLED Display\r\n50MP + 50MP + 8MP | 50MP Front Camera\r\n6500 mAh Li-ion battery Battery\r\nSnapdragon 7 Gen 4 Processor\r\n1 Year Warranty on Handset and 6 Months Warranty on Accessories
7                       8 GB RAM | 256 GB ROM\r\n16.74 cm (6.59 inches) Full HD+ AMOLED Display\r\n50MP + 50MP + 8MP | 50MP Front Camera\r\n6500 mAh Li-ion battery Battery\r\nSnapdragon 7 Gen 4 Processor\r\n1 Year Warranty on Handset and 6 Months Warranty on Accessories
8                                         12 GB RAM | 256 GB ROM\r\n16.94 cm (6.67 inch) Full HD+ AMOLED Display\r\n50MP + 50MP + 50MP | 32MP Front Camera\r\n6200 mAh Battery\r\nDimensity 9400+ Processor\r\n1 Year Warranty on Handset and 6 Months Warranty on Accessories
9                          8 GB RAM | 128 GB ROM\r\n17.27 cm (6.8 inch) Full HD+ AMOLED Display\r\n50MP + 8MP | Yes\r\n10001 mAh Battery\r\nDimensity 7400 Ultra Processor\r\n1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for Inbox Accessories
10                         8 GB RAM | 256 GB ROM\r\n16.94 cm (6.67 inch) Full HD+ AMOLED Display\r\n50MP + 50MP + 8MP | 20MP Front Camera\r\n6200 mAh Battery\r\n7s Gen 3 Processor\r\n1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories
11                                                                                   4 GB RAM | 64 GB ROM\r\n17.27 cm (6.8 inch) HD+ Display\r\n13MP Rear Camera\r\n7000 mAh Battery\r\nMediaTek Dimensity 6360 Apex Processor\r\nOne year of handset six month of accessories
12                                                   8 GB RAM | 128 GB ROM\r\n16.74 cm (6.59 inch) Full HD+ Display\r\n50MP + 8MP + 2MP | 50MP Front Camera\r\n5600 mAh Battery\r\nDimensity 8350 Processor\r\n1 Year Warranty on Handset and 6 Months Warranty on Accessories
13                                                   8 GB RAM | 128 GB ROM\r\n16.74 cm (6.59 inch) Full HD+ Display\r\n50MP + 8MP + 2MP | 50MP Front Camera\r\n5600 mAh Battery\r\nDimensity 8350 Processor\r\n1 Year Warranty on Handset and 6 Months Warranty on Accessories
14                                                                                          12 GB RAM | 256 GB ROM\r\n16.0 cm (6.3 inch) Quad HD+ Display\r\n48MP + 13MP + 10.8MP | 10.5MP Front Camera\r\n4970 mAh Battery\r\nTensor G5 Processor\r\n1 Year Domestic Warranty
15                           12 GB RAM | 512 GB ROM\r\n17.35 cm (6.83 inch) Display\r\n50MP Rear Camera\r\n7400 mAh Battery\r\n1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including batteries from the date of purchase
16                                 8 GB RAM | 128 GB ROM | Expandable Upto 1 TB\r\n17.2 cm (6.77 inch) Full HD+ Display\r\n50MP Rear Camera | 20MP Front Camera\r\n5520 mAh Battery\r\n1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories
17                                                8 GB RAM | 256 GB ROM\r\n16.03 cm (6.31 inch) Full HD+ AMOLED Display\r\n50MP + 50MP + 8MP | 50MP Front Camera\r\n6500 mAh Battery\r\nSnapdragon 8 Gen 5 Processor\r\n1 Year for Handset and 6 Months for In-box Accessories
18                                                                                         6 GB RAM | 256 GB ROM\r\n17.12 cm (6.74 inch) Display\r\n50MP Rear Camera\r\n6500 mAh Battery\r\nMediatek Dimensity 6300 Processor\r\nOne Year of Handset six months of Accessories
19                                                                                  4 GB RAM | 128 GB ROM\r\n17.27 cm (6.8 inch) HD+ Display\r\n13MP Rear Camera\r\n7000 mAh Battery\r\nMediaTek Dimensity 6360 Apex Processor\r\nOne year of handset six month of accessories
Name: other info, dtype: str

In [211]:
ram = df['other info'].str.split('|').str[0]
ram = ram.str.replace('RAM', '')

display_size = df['other info'].str.extract(r'\((.*?)\)')

df['other info'] = df['other info'].str.split('\r\n')
battery = df['other info'].str[3]
battery = battery.str.replace('Battery', '')

df.insert(7, 'ram', ram)
df.insert(8, 'display_size', display_size)
df.insert(9, 'battery', battery)

In [212]:
df = df.drop(columns='other info')

In [213]:
df

,model name,model color,storage,review,rating,star rating,discount,ram,display_size,battery
0,REDMI 11 Prime 5G,Meadow Green,64 GB,262,"4,687",4.2,No Discount,4 GB,6.58 inch,5000 mAh
1,realme GT 8 Pro,Diary White,512 GB,19,99,4.5,9% off,16 GB,6.79 inch,7000 mAh
2,OnePlus 11 5G,Eternal Green,256 GB,165,"1,900",4.5,No Discount,16 GB,6.7 inch,5000 mAh
3,IQOO Z11 Lite 5G,Solar Flame,256 GB,0,0,0.0,22% off,6 GB,6.74 inch,6500 mAh
4,realme P4R 5G,Silver Glare,128 GB,259,"3,219",4.4,45% off,6 GB,6.8 inch,8000 mAh Lithium-ion polymer
...,...,...,...,...,...,...,...,...,...,...
91,realme 16 Pro+ 5G,Master Grey,256 GB,123,855,4.6,5% off,12 GB,6.8 inch,7000 mAh
92,IQOO 15R 5G,Dark Knight,256 GB,42,330,4.7,3% off,8 GB,6.59 inch,7600 mAh
93,Samsung Galaxy S24 5G Snapdragon,Onyx Black,128 GB,"4,568","57,433",4.6,33% off,8 GB,6.2 inch,4000 mAh
94,OPPO Reno16 5G,Starry White,256 GB,9,37,4.4,32% off,12 GB,6.32 inch,6700 mAh lithium-ion polymer
95,Ai+ Nova 2 Neo 5G,Red,64 GB,109,987,4.4,22% off,4 GB,6.745 inch,6000 mAh Li-polymer

In [214]:
df.shape

(96, 10)